### ISSUE TITLE
Account screen 에서 update function 빼기

### ISSUE THREAD

**Issue by Dirtfy** [Dirtfy/PPP#15]
기존 data change 시 view에서 최근 값으로 recompose하기 위해 존재하던 update function들이 account screen part에서 deprecated 되었습니다.

더 이상 update function을 호출 하더라도 새로운 data로 바로 refresh가 됨을 보장할 수 없습니다.

ScreenState 변수를 참조하세요

**Comment by Dirtfy** [comment]
Dev 브랜치에서 fetch 받으세요

**Comment by Dirtfy** [comment]
@DongGi-create 다 해서 dev branch에 머지 됐으면 close 해줘

**Comment by Dirtfy** [comment]
@DongGi-create close 왜 안 해!

**Comment by DongGi-create** [comment]
@Dirtfy 혹시 모를 상황을 대비해서 (재사용할 경우) 일단 두고 마지막에 지우겠습니다.
