### ISSUE TITLE
입력 타입에 맞게 키보드 나오게 수정

### ISSUE THREAD

**Issue by Dirtfy** [Dirtfy/PPP#16]
현재 숫자 입력이 필요한곳도 기본 키보드가 올라오는데 상황에 맞게 나오도록 변경해주세요.

예시:
포인트 사용시 입력 타입 = 숫자
-> qwerty 자판이 아닌 숫자 다이얼 자판이 나와야 함

**Comment by DongGi-create** [comment]
해결 完

**Comment by Dirtfy** [comment]
Dev로 Merge 했나

**Comment by Dirtfy** [comment]
Dev로 Merge 했나

Merge 후에 close 해줘

**Comment by DongGi-create** [comment]
Merge 완료
