### ISSUE TITLE
View layer 에서 error catch

### ISSUE THREAD

**Issue by Dirtfy** [Dirtfy/PPP#19]
Controller 안의 ScreenState 변수를 참조하여 error massage를 보여주는 view 구현해주세요

**Comment by WeGlonD** [comment]
AccountCreateScreen 에서, 현재 뷰모델에 회원가입 request 하고, 그 직후에 다이얼로그를 종료한다.
서버로의 요청이 실패했을 경우의 대처가 요구된다.

**Comment by DongGi-create** [comment]
@Dirtfy 당신이 만든 alert dialog는 별로인가요?
![Screenshot_20241110_171728_PPP.jpg](https://github.com/user-attachments/assets/525e906f-ede1-4685-8305-09dfa2e0d5ca)

이렇게 뜨도록 했는데 이 뷰로도 충분한듯 해서..
원하는 뷰가 있다면 반영하겠음...

**Comment by Dirtfy** [comment]
👍 
근데 retry 필요한것도 아닌것도 있지않나
그것만 구분돼서 구현되면 좋을듯
