### ISSUE TITLE
[dev-emit_flow_state] Account Main Screen Loading 화면 안 뜸

### ISSUE THREAD

**Issue by Dirtfy** [Dirtfy/PPP#3]
현재 account list 불러올 때 loading 화면이 나오지 않음

1. 최초 account screen 진입 시
2. account list 를 다시 받아 올 때

2는 viewmodel에서 service에 요청 전 screen state 에 loading flag 변수 업데이트 해주면 될 듯
1은 원인 파악이 필요할 듯

확인해줘잉~

**Comment by Dirtfy** [comment]
2도 문제가 있네...
다른 곳에서 DB 수정이 생기면 loading이 안 뜨고 list가 수정될 수 있음

**Comment by Dirtfy** [comment]
1은 StateFlow.value 가 업데이트 될 때 바로 complete로 바껴서 그런듯

**Comment by WeGlonD** [comment]
[1]
해결됨

[2]
의견 조율 필요.

- DB 수정이 일어나면 바로 가져오지 않고, 변경사항을 가져오는 floating button, push notification 등을 띄우기
- DB 수정을 바로 UI에 반영하기

개인적인 의견으로는 바로 반영해도 상관 없을 것 같음.
Table Merge 기능만 Lock 적용, transaction 적용 하면 UI 변경상 크게 지장이 없을 것으로 보인다.
