### ISSUE TITLE
account detail balance update bug

### ISSUE THREAD

**Issue by Dirtfy** [Dirtfy/PPP#36]
detial dialog에서 계좌에 충전하거나 사용해도
계좌 잔고 업데이트가 바로 안됨

**Comment by DongGi-create** [comment]
![image](https://github.com/user-attachments/assets/139fe91c-70c7-4dcf-949f-3cc352be933c)
@Dirtfy @WeGlonD 
 uiAccount를 따로 업데이트하는 함수를 만들어야 하지 않을까 그래야 updateNowAccount를 할때 변경된 UiAccount를 전달해 줄 수 있을거 같은데
+ 누르면 -> addRecord되고 uiAccount 변경하고 updatenowAccount 해야 하지 않을까 싶네요
updateNewAccountRecord()처럼 뭔가 uiAccount변경함수가 있어야 할거같기도 하고.
다른 방법이 있다면 알려주세요...

**Comment by WeGlonD** [comment]
> ![image](https://github.com/user-attachments/assets/139fe91c-70c7-4dcf-949f-3cc352be933c)
> @Dirtfy @WeGlonD 
>  uiAccount를 따로 업데이트하는 함수를 만들어야 하지 않을까 그래야 updateNowAccount를 할때 변경된 UiAccount를 전달해 줄 수 있을거 같은데
> "+" 누르면 -> addRecord되고 uiAccount 변경하고 updatenowAccount 해야 하지 않을까 싶네요
> updateNewAccountRecord()처럼 뭔가 uiAccount변경함수가 있어야 할거같기도 하고.
> 다른 방법이 있다면 알려주세요...

뭔말이고 이게
