### ISSUE TITLE
account detail dialog size 고정 필요

### ISSUE THREAD

**Issue by Dirtfy** [Dirtfy/PPP#37]
account detail dialog size 가 

1. 로딩 중일 때
2. 로딩이 완료되었을 때  
2-1. 목록이 없을 때
2-2. 목록이 있을 때

다 다르게 나와서 사용자가 터치를 할 때 어디를 터치해야 할 지 파악하기 어렵다고 생각해
한가지 사이즈로 고정하는게 좋지 않을까

**Comment by DongGi-create** [comment]
@Dirtfy 음 난 저게 더 좋다 생각했는데 그럼 목록이 없든 있든간에 일정 빈공간을 두는 것이 좋아 보인다는건가?

**Comment by Dirtfy** [comment]
난 예상이 되는 UI가 좋다고 생각해서 
만약 목록의 길이에 따라서 dialog 위치가 바뀌면 어디를 터치해야할지 예상하기 어렵잖아
그냥 빈칸으로 두는건 로딩중인거나 아니면 다른걸로 착각할 수도 있으니까 목록이 없다는 설명글? 같은거 하나 넣어주는게 좋을것 같은데
뭐 어디까지나 내 생각이니까 너가 그게 더 좋아보인 이유를 말해주면 좋을것 같다.

**Comment by DongGi-create** [comment]
굿 곧 반영하겠음
