### ISSUE TITLE
OnRetryClick이 필요한가 있다면 어떤 기능을 넣어야 할까?

### ISSUE THREAD

**Issue by DongGi-create** [Dirtfy/PPP#45]

**Comment by Dirtfy** [comment]
사용자 실수(중복되는 계정 id나 메뉴 이름 등등)말고는 retry가 있어야 하지 않을까?
실제로 retry해 봐야지

그리고 @WeGlonD flow에 retryWhen인가 그거 있거든 그거 추가하는것도 좋을듯
