### ISSUE TITLE
pull request 말고는 rebase 해보아요~

### ISSUE THREAD

**Issue by Dirtfy** [Dirtfy/PPP#50]
merge를 쓰면 git history가 복잡해 지니까
혼자 쓰는 branch에서도 rebase를 써보아요
당연히 dev 브랜치 있는 내용을 내 브랜치에 받아 올 때도 rebase를 쓰면 좋겠죠 ^^

반박은 환영이야~ (수용할지는 고민해 볼게)

읽었으면 코멘트나 이모지나 남겨주세요~

**Comment by DongGi-create** [comment]
rebase 어려워요

**Comment by Dirtfy** [comment]
자넨 할 수 있어!!
