### ISSUE TITLE
UiState 추가 건의

### ISSUE THREAD

**Issue by DongGi-create** [Dirtfy/PPP#55]
![image](https://github.com/user-attachments/assets/348a54f0-688b-4b2f-8cab-470949f3ca7b)
혹시 상태 Idle을 추가할 수 있을까요?
다이얼로그의 경우 그냥 평소 경우(Idle) 와 어떤 함수를 동작하고 완료됐다는 상황(Complete)이 같아서 복잡한 상황의 경우 실행할 수가 없습니다.

Idle  ------- > Fun동작    Loading -> Complete  (Dialog 종료)
------------------------------------ -> Error        ->  다시 Fun 동작  -> Complete (Dialog 종료)
Complete 상태가 되면 dialog 종료

지금 모든 Idle상태가 Complete로 돼있으니 (함수 성공의 상태)Success 상태를 추가 하는 것도 괜찮을 것 같습니다
Ex)
when (state){
Idle -> { }
Complete -> {다이얼로그 종료} 
Fail -> {Fail view 띄우기}
}

다른 의견도 환영입니다...

**Comment by Dirtfy** [comment]
state가 하나 더 생기면 다른 feature들의 controller, view 모두 변경해야하니 신중하게...
그리고 dialog는 mode로 조절하고 있으니 더 면밀히 검토해보고...
state graph가 너무 복잡해지면 좀 그러니 일단 보류..
다른 부분에서 문제가 있어서 그런걸 수 있으니...
