### ISSUE TITLE
안 쓰는 브랜치는 삭제하는게 좋을까?

### ISSUE THREAD

**Issue by Dirtfy** [Dirtfy/PPP#58]
squash and merge하면 git history들이 사라지는데
그래서 commit message를 잘 상세하게? 적어달라고는 했지만
역시 역사를 잊은 민족에게 미래는 없다...
고민이 되는것이에요

여러분의 선택은?!?!?

**Comment by Dirtfy** [comment]
git history가 브랜치에 남아있는데 삭제하면 그 history가 사라져서 이런 생각이 들었습니다..
history를 보존하고 싶기도 하고 깔끔하게 유지하고 싶기도 하고 
그 사이에서의 고뇌랄까..?

**Comment by WeGlonD** [comment]
흠..

커밋 메시지만 유지하는거도 괜찮으면
Squash and merge 할때 커밋 메시지 쓰는 방식을
규칙을 정해서 문서화 하면 괜찮을 듯

변경사항을 커밋별로 따로 보는 그 히스토리를 남기려면
PR을 좀 더 세세하게 하는 수 밖에...

**Comment by Dirtfy** [comment]
흠.. 커밋별로 볼 필요까지는 없을것 같고 
issue를 항상 올리고 issue 브랜치를 merge하는 걸로 하면 괜찮을 거 같은데
대신 그럼 issue를 잘 분리해서 올려야 될거같긴해

난 뭐랄까 history를 정리하려고 했던게 
어떤 기능들이나 아키텍쳐가 어떤 순서로 적용되었는지 확인하고
그걸 바탕으로 문제가 생겼을 때 어떤 commit으로 restore하면 좋을지 잘 찾을 수 있지 않을까 싶어서 그랬던 거지

그래서 squash ans merge로 git history를 보기 쉽게 commit을 줄이고 
추가된 또는 변경된 내용이 어떤건지는 issue로 남기고
그러면 좋지 않을까..?

**Comment by WeGlonD** [comment]
삭제하세요
PR 찾아가면 볼 수 있잖아요 커밋 히스토리
