### ISSUE TITLE
Table screen table merge 기능 직관적으로 만들기

### ISSUE THREAD

**Issue by Dirtfy** [Dirtfy/PPP#6]
현재 table long click 으로 구현되어있지만 사용자가 어떻게 long click 하면 된다는 걸 알 수 있지?

차라리 버튼을 하나 만드는게 직관적일것 같음 디자인은 좀더 구려지겠지

다른 아이디어가 있다면 환영이에요 ^^

**Comment by DongGi-create** [comment]
일단 내 브랜치 적용 완료

**Comment by Dirtfy** [comment]
👍  역시 동기야
