### ISSUE TITLE
retry... 기능 구현

### ISSUE THREAD

**Issue by DongGi-create** [Dirtfy/PPP#66]
stream의 경우 retry 기능을 stream에 직접 추가하는 방향이 좋을 것 같아 건의드립니다.
부탁해용~

**Comment by WeGlonD** [comment]
논의 결과 retry 폐지하기로 했습니다.

**Comment by DongGi-create** [comment]
이유가 뭔가요?
retry 기능을 아예 안하나요?

**Comment by Dirtfy** [comment]
아니 
아직 잘 모르겠다..
이야기가 나오긴 했는데
있으면 좋지 않을까
우선순위는 좀 떨어지긴해..

**Comment by DongGi-create** [comment]
그러먄 일단 보류해두고 상의합시다...

**Comment by DongGi-create** [comment]
소통 메모...
