### ISSUE TITLE
음... AddAccount관련 문의

### ISSUE THREAD

**Issue by DongGi-create** [Dirtfy/PPP#67]
AccountScreen -  AccountViewModel
-> AccountCreateImpl (AddAccount함수 구현)
-> Account....

AccountScreen에서 AccountMode에 따라 Create Dialog가 켜지고 꺼짐 (Main 모드이면 CreateDialog가 꺼지는 그런 로직)
여기서 그러면 AddAccount가 Success 즉 collect 될 때 setmode함수를 통해 Main으로 바꾸면 될 것 같다고 논의 했었음..
다만 setMode는 최상위 즉 AccountviewModel에 구현이 되어 있는데
AccountcreateImpl 하위에서 상위에 구현된 함수를 불러다 써도 되나요...???

**Comment by Dirtfy** [comment]
전에 말했던 함수에 파라미터로 onComplete 추가해서 쓰는거?
난 그 방법이 괜찮을거 같은데?

**Comment by DongGi-create** [comment]
되긴 되는거 같은데 로딩때 로딩 UI띄우는게 애매해지네...

**Comment by Dirtfy** [comment]
아 그래?
UiState는 함수안에서 세팅 해주지 않나?
