### ISSUE TITLE
의문밖에 들지 않는 로직 RecordDetailViewModel.updateNowRecord()

### ISSUE THREAD

**Issue by WeGlonD** [Dirtfy/PPP#71]
의문이 드는 코드의 원본이다.
```
    override suspend fun updateNowRecord(record: UiRecord) {
        // TODO 의문 밖에 들지 않는 로직
        val type = record.type.split("-")[0].trim()
        var newValue = if (type == DataRecordType.Card.name ||
            type == DataRecordType.Cash.name) {
            record.copy(type = type) // split 안 된거는 원본과 같은데 왜..
        } else {
            record // split 된 거는 안씀?
        }
        newValue = newValue.copy(timestamp = newValue.timestamp.substring(0, 16))

        _screenData.update { it.copy(nowRecord = newValue) }
        _updateRecordDetailList(record)
    }
```

UiRecord의 type 변수에 들어가는 값에는 3가지 경우가 있다.
"Card", "Cash", "<point사용계정번호> - <추가정보>"

그래서 위의 코드는 결과적으론 다음 코드와 모든 경우에서 같은 결과를 도출한다.
```
    override suspend fun updateNowRecord(record: UiRecord) {
        val newValue = record.copy(timestamp = record.timestamp.substring(0, 16))

        _screenData.update { it.copy(nowRecord = newValue) }
        _updateRecordDetailList(record)
    }
```

뭔가 하려다가 잘못짠 코드인것은 확실하나 코드의 의도를 모르겠다.
지금 #53 진행중인데, 코드의 의도를 알게된다면 해당 코드도 수정할 예정.

**Comment by Dirtfy** [comment]
그.. 미안합니다!
그냥 지워줘요!
나도 왜 있는지 모르겠네요!
🤔

**Comment by WeGlonD** [comment]
@Dirtfy 

![Screenshot_20241114_181334_PPP.jpg](https://github.com/user-attachments/assets/9c2d7471-bc68-40b9-8904-4542ddddc5ec)

ㅋㅋㅋㅋㅋㅋㅋ
Cash - custom 이라니 이런게 있을줄이야

근데 custom이 아닌 Cash도 있나?

**Comment by DongGi-create** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
근데 Cash-custom 뭐임 ㄷㄷ

**Comment by WeGlonD** [comment]
다시 부활시킬까? custom 안 보이게

**Comment by Dirtfy** [comment]
그래야할듯 ㅋㅋㅋ 
아니면 custom붙이는 부분은 바꿔도 될거 같고

**Comment by WeGlonD** [comment]
> 그래야할듯 ㅋㅋㅋ 아니면 custom붙이는 부분은 바꿔도 될거 같고

그니까.. custom을 안붙이게 바꿀까? 아니면 그냥 저 코드 부활시켜?
둘 중에 어떻게 해야할지 모르겠다.
개인적으론 custom 안붙이게 바꾸는게 나은거 같긴 해
