### ISSUE TITLE
#73 PR관련

### ISSUE THREAD

**Issue by DongGi-create** [Dirtfy/PPP#74]
Retry...
![image](https://github.com/user-attachments/assets/b4be16b9-c893-48d5-843a-d4668b51d8b6)
다음과 같은 상황에서 Error가 난다면 View에서 Fail을 캐치하더라도 Retry를 시킬 방향에 대해 모호하다.

![image](https://github.com/user-attachments/assets/a3916781-8b13-449b-a191-73f8dfbc9d00)
다음과 같은 함수를 통해 Retry해도 될까..? 잘모르겠음...

그리고 된다 하더라도 모든 State에서 Flow마다 다 구현한다면 할일도 매우 많고 코드도 길어질것이라 예상...
방법이 있다면 ADVICE PLEASE...

**Comment by Dirtfy** [comment]
다음과 같은 상황이 어떤 상황인지 잘 모르겠네.. stream을 쓸때?
stream일 때는 controller 쪽에서 retry 하는게 좋지 않을까..
