### ISSUE TITLE
raw record list 삭제

### ISSUE THREAD

**Issue by WeGlonD** [Dirtfy/PPP#77]
raw record list를 현재처럼 유지하면
record list 전체를 들고오는 현 상황에서
메모리를 2배 차지하는 낭비가 발생한다.

차라리 view를 위해 formatting 한 list만 갖고 있고,
손실된 정보는 단일 record 쿼리를 서버에 보내 수복하는게 장기적으로 나을 듯 하다.

**Comment by Dirtfy** [comment]
메모리보다 시간이 중요하다고 생각하긴 하지만
raw record list 내가 만들면서도 기분이 나쁘긴 했어
찬성이요
