### ISSUE TITLE
Record API와 Account API 분리 마저 하기!

### ISSUE THREAD

**Issue by WeGlonD** [Dirtfy/PPP#79]
@Dirtfy 가 #49 할 때, Account API 에서 record 접근하던 부분을 그냥 deprecated 처리 하고

하위 Business Logic에서는 그냥 deprecated 된 함수를 쓰도록 해놨다!

이녀석 괘씸한걸?

deprecate 시킨 것 모두 record API의 함수로 만들고 그것을 사용하도록 수정하라!

**Comment by DongGi-create** [comment]
정말 정말 괘씸하다
