### ISSUE TITLE
snapshot의 network error 처리

### ISSUE THREAD

**Issue by WeGlonD** [Dirtfy/PPP#84]
현재 네트워크에 연결되지 않은 상태에서는 캐시에서 snapshot을 가져온다.

즉 네트워크가 연결되어 있는지 아닌지 SnapshotListener 에서의 snapshot 내용으로는 판단 불가하다!

논의 결과, 네트워크가 연결되어 있지 않다면 앱의 대부분의 기능을 사용할 수 없기 때문에,

네트워크 연결되어 있지 않으면 Network Exception을 throw하자.

이는 cache에서 불러온 것인지 아닌지를 판단하여 진행하면 된다.

**Comment by WeGlonD** [comment]
[CONCLUSION]
persistent cache 대신 memory cache 를 사용하도록 변경하고,
cache에서 불러온다면 network exception을 던지도록 구현

**Comment by DongGi-create** [comment]
오
cache에서 불러옴 -> NetWork error
cache가 아닌 통신으로 받아옴 -> 정상
이건가요?

**Comment by DongGi-create** [comment]
저부분이 아까 bind -> provide와 관련된 건가요?

**Comment by WeGlonD** [comment]
> 오
> cache에서 불러옴 -> NetWork error
> cache가 아닌 통신으로 받아옴 -> 정상
> 이건가요?


> 저부분이 아까 bind -> provide와 관련된 건가요?


모두 정답입니다

위의 캐시 설정을 하기 위해서 Firestore 객체가 사용되기 전에 설정 코드를 실행해야 해서

FireStoreManager 클래스를 singleton 패턴으로 만들고 설정 코드를 실행, 멤버로 각 하위 Firestore 객체를 갖고 있도록 하고, DI 할 때 이 멤버들을 주입하도록 구현했습니다.

자세한건 PR의 FireStoreManager 클래스를 참고하세요...
