### ISSUE TITLE
Firebase Authentication 관련 궁금한점!

### ISSUE THREAD

**Issue by WeGlonD** [Dirtfy/PPP#96]
### 질문
@DongGi-create @Dirtfy 아는 게 있다면 말해주세요. 모른다면 모른다고 코멘트 부탁

1. firebase authentication으로 로그인했을 때,
여러 디바이스에서 동일한 계정에 로그인을 하면 어떻게 되는가?
2. 여러 디바이스에서 같은 계정으로 로그인하는 것을 막을 수 있는가?
3. 로그인 세션 유지 시간을 설정해줄 수 있는가?

### 질문을 하게 된 이유...
지금 Table merge에 lock 걸다가 문득
merge 모드 상태에서 폰이 꺼지면 서버에 lock field 값이 변경이 없고,
그럼 모든 디바이스가 lock을 가져갈 수 없는 상황이 된다는 문제점을 발견함.

그래서 이렇게 db에 field를 두는 게 아니라
Firebase Authentication 로그인을 활용하여, 관리자용 계정을 하나 만들고,
여러 디바이스에서 같은 계정으로 로그인하는 것을 막고,
로그인 세션을 1분 이내로 굉장히 짧게 설정한다면?

이 관리자용 계정에 로그인을 성공한 기기만 merge를 허용한다면?
merge lock을 아주 쌈@뽕하게 구현할 수 있을 것만 같다.
폰이 꺼져도 세션 유지 시간이 끝나면 알아서 서버에서도 세션유지가 안되니 로그아웃 시키지 않을까

**Comment by Dirtfy** [comment]
몰라요.. 좀 찾아보기는 할게
아이디어는 쌈@뽕 하네요

**Comment by DongGi-create** [comment]
저도 잘 모르는데 아마 디바이스 같은계정이 될듯해서 한다면 어려울듯 하네요
쌈@뽕
근데 저게 구현된다 하면 merge할때마다 로그인 해야하나요?

**Comment by Dirtfy** [comment]
> 근데 저게 구현된다 하면 merge할때마다 로그인 해야하나요?

로그인 하는 과정은 숨겨서 구현해면 될거 같긴한데

검색이랑 gpt를 통해 물어본 결과

여러 디바이스 로그인을 막는 기능은 없는거 같네

세션은 id token을 갱신해서 뭐 좀 조작할 수 있다는데 이것도 우회적인 반쪽짜리인것같고

좀 아쉽네..

**Comment by WeGlonD** [comment]
당연히 로그인은 숨겨서 할라했지

파이어베이스 이런거도 안되고 말이야

계엄령 마렵네

**Comment by WeGlonD** [comment]
일단 @DongGi-create 의 의견대로 timestamp를 추가하여 session 일정 시간이 지나면 lock을 가져올 수 있도록 구현함.
쌈@뽕하지는 않지만 User 입장에선 어떻게 구현되어 있는지 알빠 아니니까요...
